### ISSUE TITLE
MIT license?

### ISSUE THREAD

**Issue by aguynamedben** [ericjohnson/canabalt-ios#5]
I am trying to understand if Canabalt uses the MIT license.

I read here: http://blog.semisecretsoftware.com/canabalt-open-source-details-licensing-and-ex that Canabalt is open-sourced under the MIT license, but by reading the actual repo's licensing files, it's unclear if the entire content is released under MIT, or just the engine.  Is this just something that needs to be updated in the repo?

https://github.com/ericjohnson/canabalt-ios/blob/master/README.TXT - confusing
https://github.com/ericjohnson/canabalt-ios/blob/master/GAME_LICENSE.TXT - proprietary
https://github.com/ericjohnson/canabalt-ios/blob/master/flixel-ios/ENGINE_LICENSE.TXT - MIT

So, is the game itself open-sourced as well?  Or just the fixel-ios portoin?

-Ben

**Comment by ericjohnson** [comment]
Hi Ben -

From the file 'README.TXT': With the exception of code contained in the 'flixel-ios' folder, you cannot redistribute our source code from the original game. You can use our source code for personal entertainment or education purposes.

The source code in flixel-ios can be used for whatever you want (MIT style license).

Everything else you can feel free to use for personal entertainment or educational purposes. However, you cannot redistribute for personal or commercial gain. For everything _not_ in the flixel-ios, the license found in 'GAME_LICENSE.TXT' applies.

Hope that makes sense. Please let me know if you have further questions.
- Eric

**Comment by aguynamedben** [comment]
I see.  Thanks for the outstanding licensing, that clears it up.  FYI, we (at SimpleGeo) are looking to fork it for educational purposes (i.e. how to add a geo feature to your app), and we are not looking to redistribute the game or make a profit off our modifications.

-Ben
